name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Новые фичи'
    labels:
      - 'feature'
  - title: '🐛 Исправления'
    labels:
      - 'bug'
  - title: '🧹 Рефакторинг'
    labels:
      - 'refactor'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Изменения

  $CHANGES 