version: '3.8'

services:
  discord-bot:
    build: .
    container_name: discord-bot
    restart: unless-stopped
    volumes:
      - ./json:/app/json  
    environment:
      - TOKEN=${DISCORD_TOKEN}
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge