version: '3.8'
services:
  discordjbot:
    build: .
    container_name: discordjbot
    volumes:
      - ./json:/app/json
    # Если нужен порт, раскомментируйте следующую строку
    # ports:
    #   - "8080:8080"
    restart: unless-stopped