name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Check JAR version matches tag
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          JAR=target/DiscordjBot-jar-with-dependencies.jar
          MANIFEST_VERSION=$(unzip -p "$JAR" META-INF/MANIFEST.MF | grep Implementation-Version | cut -d' ' -f2 | tr -d '\r')
          echo "Tag version: $TAG_VERSION"
          echo "Manifest version: $MANIFEST_VERSION"
          if [ "$TAG_VERSION" != "$MANIFEST_VERSION" ]; then
            echo "ERROR: Version in MANIFEST.MF ($MANIFEST_VERSION) does not match tag ($TAG_VERSION)"
            exit 1
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/DiscordjBot-jar-with-dependencies.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 